name: Tag Release

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/Hass-Lynk-Co/manifest.json'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from manifest.json
        run: |
          VERSION=$(jq -r '.version' custom_components/Hass-Lynk-Co/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and Push Tag
        run: |
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
              echo "Tag $VERSION already exists."
          else
              git tag $VERSION
              git push origin $VERSION
          fi
