name: Release on Version Change

on:
  push:
    branches:
      - main
    paths:
      - custom_components/Hass-Lynk-Co/manifest.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Extract version from manifest.json
      id: version
      run: echo "::set-output name=VERSION::$(jq -r .version custom_components/Hass-Lynk-Co/manifest.json)"
      shell: bash
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ steps.version.outputs.VERSION }}"
        title: "Release v${{ steps.version.outputs.VERSION }}"
        prerelease: false
