name: Tag Release

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/Hass-Lynk-Co/manifest.json'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Extract version from manifest.json
        id: extract_version
        run: |
          echo "VERSION=$(jq -r '.version' custom_components/Hass-Lynk-Co/manifest.json)" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create Tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
